allowBuilds:
  "@reown/appkit": true
  esbuild: true
patchedDependencies:
  react18-json-view: patches/react18-json-view.patch
# TODO: remove when ParaSpell uses PAPI v3 stable
overrides:
  "@paraspell/sdk@14.1.0-rc.1>polkadot-api": "3.0.0"
  "@paraspell/sdk@14.1.0-rc.1>@polkadot-api/signers-common": "0.3.0"
  "@paraspell/sdk@14.1.0-rc.1>@polkadot-api/substrate-bindings": "0.21.0"
  "@paraspell/descriptors@14.1.0-rc.1>polkadot-api": "3.0.0"
